\documentclass[11pt,a4paper]{book} %must be first line of code
\usepackage[most]{tcolorbox}    %for fitting text into box

\begin{document}




\tcbset{colframe=blue!50!black,colback=white,colupper=red!50!black,
fonttitle=\bfseries,nobeforeafter,center title}
Text \tcbox[tcbox raise base]{Hello World}\hfill
%
\tcbox[left=0mm,right=0mm,top=0mm,bottom=0mm,boxsep=0mm,
toptitle=0.5mm,bottomtitle=0.5mm,title=My table]{%
\arrayrulecolor{blue!50!black}\renewcommand{\arraystretch}{1.2}%
\begin{tabular}{r|c|l}
One & Two & Three \\\hline\hline
Men & Mice & Lions \\\hline
Upper & Middle & Lower
\end{tabular}}\hfill
%
\tcbox[colback=blue!85!black,
left=0mm,right=0mm,top=0mm,bottom=0mm,boxsep=1mm,arc=0mm,boxrule=0.5pt,
title=My picture]{%
\includegraphics[width=5cm]{Basilica_5.png}}


\end{document}